# -*- coding: utf-8 -*-
"""Heart Disease Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o_ghpcKQc3TFuc7BDCbYrheR2QC8Ye0s
"""

import pandas as pd

df = pd.read_csv("/content/heart_disease_uci.csv")

df

df.columns

"""### **Details of Data**

**id:** (Unique id for each patient)

**age:** (Age of the patient in years)

**origin:** (place of study)

**sex:** (Male/Female)

**cp: chest pain type:**

**1.** typical angina

**2.** atypical angina

**3.** non-anginal

**4.** asymptomatic

**trestbps:** resting blood pressure (resting blood pressure (in mm Hg on admission to the hospital))

**chol:** (serum cholesterol in mg/dl)

**fbs:** (if fasting blood sugar > 120 mg/dl)

**restecg:** (resting electrocardiographic results)

**Values:** [normal, stt abnormality, lv hypertrophy]

**thalach:** maximum heart rate achieved

**exang:** exercise-induced angina (True/ False)

**oldpeak:** ST depression induced by exercise relative to rest

**slope:** the slope of the peak exercise ST segment

**ca:** number of major vessels (0-3) colored by fluoroscopy

**thal:** [normal; fixed defect; reversible defect]

**num:** the predicted attribute [0 shows no disease and 1, 2, 3 and 4 shows different level of disease]
"""

dict1['Coronary Artery Disease']['Age']

df.columns

df['age'].min(),df['age'].max()

df['cp'].unique()

df['trestbps'].unique()

df['chol'].unique()

df['fbs'].unique()

df['restecg'].unique()

df['thalch'].unique()

df['exang'].unique()

df['oldpeak'].unique()

#'slope', 'ca', 'thal', 'num'

df['slope'].unique()

df['ca'].unique()

df['thal'].unique()

df['num'].unique()

df.isna().sum()

df.dropna(inplace = True)

df.shape

df

df.isna().sum()

''' 'id', 'age', 'sex', 'dataset', 'cp', 'trestbps', 'chol', 'fbs',
       'restecg', 'thalch', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'num'],
      dtype='object   '''

df.replace({
    'cp': {'typical angina':0, 'asymptomatic':1, 'non-anginal':2, 'atypical angina':3},
    'fbs':{"True":1, "False":0},
    'restecg':{'lv hypertrophy':0, 'normal':1, 'st-t abnormality':2},
    'exang':{'False':0, 'True':1},
    'slope':{'downsloping':0, 'flat':1, 'upsloping':2},
    'thal':{'fixed defect':0, 'normal':1, 'reversable defect':2},



},inplace = True)

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split


from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix



X = df.drop(['id','sex','dataset','num'], axis=1)
y = df['num']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,   # IMPORTANT
    random_state=42
)
model = RandomForestClassifier(
    n_estimators=300,
    class_weight='balanced',
    random_state=42
)

# Step 5: Train the model
model.fit(X_train, y_train)

"""## **MODEL TESTING:**"""

y_pred = model.predict(X_test)

"""## **MODEL EVALUATION:**"""

model.score(X_test,y_test)

# Step 7: Evaluate Model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

"""### **Feature importance**"""

import pandas as pd

feature_importance = pd.Series(
    model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

print(feature_importance)

import matplotlib.pyplot as plt
import pandas as pd

feature_importance = pd.Series(
    model.feature_importances_,
    index=X.columns
).sort_values(ascending=True)

feature_importance.plot(kind='barh')
plt.title("Feature Importance")
plt.show()

"""### **balancing the imbalance dataset**"""

pip install imbalanced-learn

from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split

# Stratified split (IMPORTANT)
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

# Apply SMOTE only on training data
sm = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = sm.fit_resample(X_train, y_train)

print("Before SMOTE:", y_train.value_counts())
print("After SMOTE:", pd.Series(y_train_resampled).value_counts())

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=300,
    random_state=42
)

model.fit(X_train_resampled, y_train_resampled)

y_pred1 = model.predict(X_test)

model.score(X_train_resampled, y_train_resampled)

#metrics



print("Accuracy:", accuracy_score(y_test, y_pred1))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred1))
print("\nClassification Report:\n", classification_report(y_test, y_pred1))

"""## **USER INPUT**"""

#|-----------------------------------------------------------------------------------------------------------|
#<--------------------------------------------user input ---------------------------------------------------->
#|-----------------------------------------------------------------------------------------------------------|



id = int(input("Enter you id : "))
age = int(input("Enter you age : "))
sex = input("Enter if female :0 , male:1 : ")
cp  = int(input("Enter the chestpain number ('typical angina':0, 'asymptomatic':1, 'non-anginal':2, 'atypical angina':3) : "))
trestbps = float(input(" resting blood pressure  : "))
chol = float(input("enter the cholesterol number : "))
fbs  = int(input("Enter the fasting blood sugar using these ({'True':1, 'False':0}) : "))
restecg = int(input(" Enter you resting ECG results : "))
thalch  = float(input("Enter your maximum heart rate acheieved : "))
exang = int(input(" Enter (exercise-induced angina (True -1/ False-0)) : "))
oldpeak = float(input(" Enter (ST depression induced by exercise relative to rest) : "))
slope  = int(input("Enter (the slope of the peak exercise ST segment){'downsloping':0, 'flat':1, 'upsloping':2} : "))
ca    = int(input(" Enter (number of major vessels (0-3) colored by fluoroscopy) "))
thal  = int(input("Enter 'result of thallium stress test' {'fixed defect':0, 'normal':1, 'reversable defect':2} : "))


X = [age,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal]

y_pred = model.predict([X])

#[id,58, 0, 150, 260, 1, 1, 120, 1, 2.3, 2, 2, 7]  --- this list of values are related to the - Coronary Artery Disease
#you can check with all the arrays present in the header ,for some heart diseases

y_pred

"""## **Heart Diseases Detection:**

### **Heart related Diseases: [id, age, sex, cp, trestbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, thal]**
**1.Coronary Artery Disease  : [ id,58, 0, 150, 260, 1, 1, 120, 1, 2.3, 2, 2, 7]**

**2.Heart Attack (Myocardial Infarction) :[id, 62, 0, 160, 290, 1, 2, 110, 1, 3.5, 3, 3, 6]**

**3.Angina : [id, 54, 0, 145, 240, 0, 1, 135, 1, 1.8, 2, 1, 7]**

**4.Heart Failure : [id, 67, 2, 155, 270, 1, 2, 100, 1, 2.8, 2, 2, 6]**

**5.Arrhythmia [id, 45, 3, 130, 210, 0, 1, 150, 0, 0.5, 1, 0, 3]**

**6.Atherosclerosis : [id, 60, 2, 148, 280, 1, 1, 125, 1, 2.0, 2, 2, 7]**

**7.Cardiac Arrest : [id, 65, 0, 170, 300, 1, 2, 95, 1, 4.0, 3, 3, 6]**
"""

dict1 ={
    "Coronary Artery Disease" :{'Age':58, 'Chest pain type':0, 'BP':150, 'Cholesterol':260,
       'FBS over 120':1, 'EKG results':1, 'Max HR':120, 'Exercise angina':1,
       'ST depression':2.3, 'Slope of ST':2, 'Number of vessels fluro':2, 'Thallium':7},

    "Heart Attack (Myocardial Infarction)" :{'Age':62, 'Chest pain type':0, 'BP':160, 'Cholesterol':290,
       'FBS over 120':1, 'EKG results':2, 'Max HR':110, 'Exercise angina':1,
       'ST depression':3.5, 'Slope of ST':3, 'Number of vessels fluro':3, 'Thallium':6},


     "Angina" :{'Age':54, 'Chest pain type':0, 'BP':145, 'Cholesterol':240,
       'FBS over 120':0, 'EKG results':1, 'Max HR':135, 'Exercise angina':1,
       'ST depression':1.8, 'Slope of ST':2, 'Number of vessels fluro':1, 'Thallium':7},

    "Heart Failure" :{'Age':67, 'Chest pain type':2, 'BP':155, 'Cholesterol':270,
       'FBS over 120':1, 'EKG results':2, 'Max HR':100, 'Exercise angina':1,
       'ST depression':2.8, 'Slope of ST':2, 'Number of vessels fluro':2, 'Thallium':6},

     "Arrhythmia" :{'Age':45, 'Chest pain type':3, 'BP':130, 'Cholesterol':210,
       'FBS over 120':0, 'EKG results':1, 'Max HR':150, 'Exercise angina':0,
       'ST depression':0.5, 'Slope of ST':1, 'Number of vessels fluro':0, 'Thallium':3},


     "Atherosclerosis" :{'Age':60, 'Chest pain type':2, 'BP':148, 'Cholesterol':280,
       'FBS over 120':1, 'EKG results':1, 'Max HR':125, 'Exercise angina':1,
       'ST depression':2.0, 'Slope of ST':2, 'Number of vessels fluro':2, 'Thallium':7},


     "Cardiac Arrest" :{'Age':65, 'Chest pain type':0, 'BP':170, 'Cholesterol':300,
       'FBS over 120':1, 'EKG results':2, 'Max HR':95, 'Exercise angina':1,
       'ST depression':4.0, 'Slope of ST':3, 'Number of vessels fluro':3, 'Thallium':6}

}

df.rename(columns={
    'age': 'Age',
    'cp': 'Chest pain type',
    'trestbps': 'BP',
    'chol': 'Cholesterol',
    'fbs': 'FBS over 120',
    'restecg': 'EKG results',
    'thalach': 'Max HR',
    'exang': 'Exercise angina',
    'oldpeak': 'ST depression',
    'slope': 'Slope of ST',
    'ca': 'Number of vessels fluro',
    'thal': 'Thallium'
}, inplace=True)

df.info()

user_data = list(X)

age = user_data[0]
cp = user_data[1]
bp = user_data[2]
chol = user_data[3]
fbs = user_data[4]
ekg = user_data[5]
max_hr = user_data[6]
exang = user_data[7]
oldpeak = user_data[8]
slope = user_data[9]
vessels = user_data[10]
thal = user_data[11]


# 🔴 Cardiac Arrest (Most Severe)
if bp >= 170 and chol >= 300 and oldpeak >= 4.0 and vessels >= 3:
    print("Cardiac Arrest")

# 🔴 Heart Attack
elif bp >= 160 and chol >= 280 and oldpeak >= 3.0 and vessels >= 3:
    print("Heart Attack (Myocardial Infarction)")

# 🔵 Coronary Artery Disease
elif vessels >= 2 and chol >= 250 and oldpeak >= 2.0:
    print("Coronary Artery Disease")

# 🟣 Atherosclerosis
elif chol >= 270 and vessels >= 2 and oldpeak >= 2.0:
    print("Atherosclerosis")

# 🟡 Heart Failure
elif max_hr <= 100 and oldpeak >= 2.5 and exang == 1:
    print("Heart Failure")

# 🟠 Angina
elif exang == 1 and 1.5 <= oldpeak <= 2.5 and vessels <= 1:
    print("Angina")

# 🟢 Arrhythmia
elif cp == 3 and max_hr >= 150 and vessels == 0 and oldpeak <= 1:
    print("Arrhythmia")

else:
    print("Condition unclear – further medical evaluation required")